import {
  type Project,
  type ProgressUpdate,
  type ProjectDocument,
  type PaymentMilestone,
  type PaymentSummary,
  type Lead,
  type Notification,
  type AdminStats,
  type User,
} from "@/types";

// ============================================
// Mock Users
// ============================================

export const MOCK_CUSTOMER: User = {
  id: "cust-001",
  name: "Vikram Patel",
  email: "vikram@example.com",
  phone: "+91 99887 76655",
  role: "customer",
  createdAt: "2025-03-15",
};

export const MOCK_ADMIN: User = {
  id: "admin-001",
  name: "Ananya Reddy",
  email: "ananya@brickbasket.in",
  phone: "+91 98765 43210",
  role: "admin",
  createdAt: "2024-01-01",
};

export const MOCK_ENGINEER: User = {
  id: "eng-001",
  name: "Arjun Nair",
  email: "arjun@brickbasket.in",
  phone: "+91 97654 32100",
  role: "engineer",
  createdAt: "2024-06-01",
};

// ============================================
// Mock Project
// ============================================

export const MOCK_PROJECT: Project = {
  id: "proj-001",
  name: "Patel Residence",
  customerId: "cust-001",
  customerName: "Vikram Patel",
  siteAddress: "Plot 42, Sunrise Layout, Whitefield",
  city: "Bengaluru",
  plotSize: "2,400 sq.ft",
  builtUpArea: "1,800 sq.ft",
  startDate: "2025-06-01",
  expectedCompletion: "2026-04-30",
  currentStage: "walls",
  status: "in_progress",
  completionPercentage: 42,
  assignedEngineer: "Arjun Nair",
  totalValue: 3780000,
  amountPaid: 1512000,
  milestones: [
    {
      id: "m1",
      stage: "planning",
      title: "Planning & Design",
      status: "completed",
      startDate: "2025-06-01",
      completedDate: "2025-07-15",
      description: "Design finalization and government approvals",
      photoCount: 12,
      notes: "All approvals obtained. Design finalized with client.",
    },
    {
      id: "m2",
      stage: "foundation",
      title: "Foundation",
      status: "completed",
      startDate: "2025-07-20",
      completedDate: "2025-09-10",
      description: "Excavation and foundation laying",
      photoCount: 45,
      notes: "Foundation completed. Soil quality excellent.",
    },
    {
      id: "m3",
      stage: "columns",
      title: "Columns & Beams",
      status: "completed",
      startDate: "2025-09-15",
      completedDate: "2025-11-20",
      description: "Structural framework erected",
      photoCount: 38,
      notes: "All columns and beams completed per structural plan.",
    },
    {
      id: "m4",
      stage: "walls",
      title: "Walls",
      status: "in_progress",
      startDate: "2025-11-25",
      description: "Brick and block work in progress",
      photoCount: 22,
      notes: "Ground floor walls 80% complete. First floor starting soon.",
    },
    {
      id: "m5",
      stage: "slab",
      title: "Roof Slab",
      status: "upcoming",
      description: "Roof slab casting",
      photoCount: 0,
    },
    {
      id: "m6",
      stage: "plumbing",
      title: "Plumbing",
      status: "upcoming",
      description: "Water and drainage line installation",
      photoCount: 0,
    },
    {
      id: "m7",
      stage: "electrical",
      title: "Electrical",
      status: "upcoming",
      description: "Wiring and electrical fixtures",
      photoCount: 0,
    },
    {
      id: "m8",
      stage: "finishing",
      title: "Finishing",
      status: "upcoming",
      description: "Plastering, painting, and flooring",
      photoCount: 0,
    },
    {
      id: "m9",
      stage: "handover",
      title: "Handover",
      status: "upcoming",
      description: "Final inspection and key handover",
      photoCount: 0,
    },
  ],
};

// ============================================
// Mock Progress Updates
// ============================================

export const MOCK_PROGRESS_UPDATES: ProgressUpdate[] = [
  {
    id: "pu-001",
    projectId: "proj-001",
    title: "Ground floor wall work – East side completed",
    description:
      "Completed brick laying on the east wall of the ground floor. Mortar quality checked and approved. Window openings left as per design. Ready for lintel casting next week.",
    stage: "walls",
    completionPercentage: 42,
    photos: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    uploadedBy: "Arjun Nair",
    uploadedByRole: "engineer",
    date: "2026-06-14",
    time: "17:30",
  },
  {
    id: "pu-002",
    projectId: "proj-001",
    title: "Ground floor wall work – South side progress",
    description:
      "Started brick laying on south wall. Foundation alignment verified. Using Grade-A bricks as specified. 40% of south wall completed today.",
    stage: "walls",
    completionPercentage: 38,
    photos: ["/api/placeholder/800/600", "/api/placeholder/800/600"],
    uploadedBy: "Arjun Nair",
    uploadedByRole: "engineer",
    date: "2026-06-13",
    time: "18:00",
  },
  {
    id: "pu-003",
    projectId: "proj-001",
    title: "Lintel preparation and steel binding",
    description:
      "Steel reinforcement bars cut and bent for lintel. Binding work started for ground floor lintels above windows and doors. TMT bars checked for quality certification.",
    stage: "walls",
    completionPercentage: 35,
    photos: ["/api/placeholder/800/600"],
    uploadedBy: "Arjun Nair",
    uploadedByRole: "engineer",
    date: "2026-06-12",
    time: "16:45",
  },
  {
    id: "pu-004",
    projectId: "proj-001",
    title: "North wall brick work completed",
    description:
      "Completed the north-facing wall of ground floor. Checked plumb line and horizontal levels — all within tolerance. Curing started.",
    stage: "walls",
    completionPercentage: 30,
    photos: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    uploadedBy: "Arjun Nair",
    uploadedByRole: "engineer",
    date: "2026-06-10",
    time: "17:15",
  },
  {
    id: "pu-005",
    projectId: "proj-001",
    title: "Column casting completed successfully",
    description:
      "All 16 columns for ground floor have been successfully cast. M25 grade concrete used. Vibrator compaction done. Curing schedule — 7 days water curing started.",
    stage: "columns",
    completionPercentage: 25,
    photos: ["/api/placeholder/800/600", "/api/placeholder/800/600"],
    uploadedBy: "Arjun Nair",
    uploadedByRole: "engineer",
    date: "2025-11-18",
    time: "16:00",
  },
];

// ============================================
// Mock Documents
// ============================================

export const MOCK_DOCUMENTS: ProjectDocument[] = [
  {
    id: "doc-001",
    projectId: "proj-001",
    name: "Construction Agreement",
    category: "agreement",
    fileType: "pdf",
    fileSize: "2.4 MB",
    uploadDate: "2025-06-01",
    uploadedBy: "Brick Basket Team",
    url: "#",
    isVisible: true,
  },
  {
    id: "doc-002",
    projectId: "proj-001",
    name: "Architectural Plan – Ground Floor",
    category: "plan",
    fileType: "pdf",
    fileSize: "5.1 MB",
    uploadDate: "2025-06-15",
    uploadedBy: "Design Team",
    url: "#",
    isVisible: true,
  },
  {
    id: "doc-003",
    projectId: "proj-001",
    name: "Structural Drawing",
    category: "plan",
    fileType: "dwg",
    fileSize: "8.3 MB",
    uploadDate: "2025-06-20",
    uploadedBy: "Design Team",
    url: "#",
    isVisible: true,
  },
  {
    id: "doc-004",
    projectId: "proj-001",
    name: "Building Permit",
    category: "government",
    fileType: "pdf",
    fileSize: "1.2 MB",
    uploadDate: "2025-07-10",
    uploadedBy: "Brick Basket Team",
    url: "#",
    isVisible: true,
  },
  {
    id: "doc-005",
    projectId: "proj-001",
    name: "Foundation Payment Receipt",
    category: "receipt",
    fileType: "pdf",
    fileSize: "0.8 MB",
    uploadDate: "2025-09-12",
    uploadedBy: "Accounts Team",
    url: "#",
    isVisible: true,
  },
  {
    id: "doc-006",
    projectId: "proj-001",
    name: "Material Quality Certificate",
    category: "certificate",
    fileType: "pdf",
    fileSize: "1.5 MB",
    uploadDate: "2025-10-05",
    uploadedBy: "Quality Team",
    url: "#",
    isVisible: true,
  },
  {
    id: "doc-007",
    projectId: "proj-001",
    name: "First Floor Plan",
    category: "plan",
    fileType: "pdf",
    fileSize: "4.8 MB",
    uploadDate: "2025-06-15",
    uploadedBy: "Design Team",
    url: "#",
    isVisible: true,
  },
  {
    id: "doc-008",
    projectId: "proj-001",
    name: "Soil Test Report",
    category: "certificate",
    fileType: "pdf",
    fileSize: "3.2 MB",
    uploadDate: "2025-06-25",
    uploadedBy: "Testing Lab",
    url: "#",
    isVisible: true,
  },
];

// ============================================
// Mock Payments
// ============================================

export const MOCK_PAYMENT_MILESTONES: PaymentMilestone[] = [
  {
    id: "pay-001",
    projectId: "proj-001",
    name: "Booking & Design",
    amount: 378000,
    dueDate: "2025-06-01",
    paidDate: "2025-06-01",
    status: "paid",
    receiptUrl: "#",
    description: "10% — Agreement signing and design initiation",
  },
  {
    id: "pay-002",
    projectId: "proj-001",
    name: "Foundation Start",
    amount: 567000,
    dueDate: "2025-07-20",
    paidDate: "2025-07-18",
    status: "paid",
    receiptUrl: "#",
    description: "15% — Before foundation work begins",
  },
  {
    id: "pay-003",
    projectId: "proj-001",
    name: "Foundation Completion",
    amount: 567000,
    dueDate: "2025-09-15",
    paidDate: "2025-09-12",
    status: "paid",
    receiptUrl: "#",
    description: "15% — After foundation is completed and verified",
  },
  {
    id: "pay-004",
    projectId: "proj-001",
    name: "Column & Wall Stage",
    amount: 756000,
    dueDate: "2026-01-15",
    status: "pending",
    description: "20% — During structural and wall work",
  },
  {
    id: "pay-005",
    projectId: "proj-001",
    name: "Slab Completion",
    amount: 567000,
    dueDate: "2026-03-15",
    status: "pending",
    description: "15% — After roof slab is cast",
  },
  {
    id: "pay-006",
    projectId: "proj-001",
    name: "Electrical & Plumbing",
    amount: 378000,
    dueDate: "2026-05-15",
    status: "pending",
    description: "10% — During MEP work",
  },
  {
    id: "pay-007",
    projectId: "proj-001",
    name: "Finishing Work",
    amount: 378000,
    dueDate: "2026-07-15",
    status: "pending",
    description: "10% — Plastering, painting, flooring",
  },
  {
    id: "pay-008",
    projectId: "proj-001",
    name: "Final Handover",
    amount: 189000,
    dueDate: "2026-09-15",
    status: "pending",
    description: "5% — Upon final inspection and key handover",
  },
];

export const MOCK_PAYMENT_SUMMARY: PaymentSummary = {
  totalValue: 3780000,
  amountPaid: 1512000,
  amountDue: 2268000,
  nextDueDate: "2026-01-15",
  nextDueAmount: 756000,
};

// ============================================
// Mock Leads
// ============================================

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-001",
    name: "Suresh Menon",
    email: "suresh@email.com",
    phone: "+91 98765 11111",
    city: "Bengaluru",
    plotSize: "2,400 sq.ft",
    builtUpArea: "1,600 sq.ft",
    budgetRange: "₹40 – 60 Lakhs",
    homeType: "independent_house",
    servicesNeeded: ["Construction Planning", "Site Supervision"],
    timeline: "Within 1 month",
    preferredContact: "phone",
    notes: "Wants Vastu-compliant design. Has existing plot in Whitefield.",
    status: "new",
    createdAt: "2026-06-14",
  },
  {
    id: "lead-002",
    name: "Lakshmi Devi",
    email: "lakshmi@email.com",
    phone: "+91 98765 22222",
    city: "Hyderabad",
    plotSize: "3,000 sq.ft",
    builtUpArea: "2,200 sq.ft",
    budgetRange: "₹60 – 80 Lakhs",
    homeType: "duplex",
    servicesNeeded: ["Construction Planning", "Design Consultation", "Progress Tracking"],
    timeline: "1 – 3 months",
    preferredContact: "whatsapp",
    notes: "NRI client based in Dubai. Needs complete remote management.",
    status: "contacted",
    assignedTo: "Priya Sharma",
    createdAt: "2026-06-12",
    lastContactedAt: "2026-06-13",
  },
  {
    id: "lead-003",
    name: "Arun Krishnan",
    email: "arun@email.com",
    phone: "+91 98765 33333",
    city: "Chennai",
    plotSize: "1,800 sq.ft",
    builtUpArea: "1,200 sq.ft",
    budgetRange: "₹20 – 40 Lakhs",
    homeType: "row_house",
    servicesNeeded: ["Construction Planning"],
    timeline: "3 – 6 months",
    preferredContact: "email",
    notes: "Looking for basic construction management. Budget-conscious.",
    status: "qualified",
    assignedTo: "Ravi Kumar",
    createdAt: "2026-06-10",
    lastContactedAt: "2026-06-12",
  },
  {
    id: "lead-004",
    name: "Fatima Begum",
    email: "fatima@email.com",
    phone: "+91 98765 44444",
    city: "Bengaluru",
    plotSize: "4,000 sq.ft",
    builtUpArea: "3,200 sq.ft",
    budgetRange: "₹1 – 2 Crore",
    homeType: "villa",
    servicesNeeded: [
      "Construction Planning",
      "Design Consultation",
      "Site Supervision",
      "Progress Tracking",
      "Material Coordination",
    ],
    timeline: "Immediately",
    preferredContact: "phone",
    notes: "Premium client. Wants full-service villa construction with interior design.",
    status: "converted",
    assignedTo: "Ananya Reddy",
    createdAt: "2026-06-05",
    lastContactedAt: "2026-06-08",
  },
  {
    id: "lead-005",
    name: "Deepak Joshi",
    email: "deepak@email.com",
    phone: "+91 98765 55555",
    city: "Pune",
    plotSize: "1,500 sq.ft",
    builtUpArea: "1,000 sq.ft",
    budgetRange: "Under ₹20 Lakhs",
    homeType: "independent_house",
    servicesNeeded: ["Cost Estimation"],
    timeline: "Just exploring",
    preferredContact: "email",
    notes: "Very early stage. Just wants a cost estimate.",
    status: "rejected",
    assignedTo: "Ravi Kumar",
    createdAt: "2026-06-01",
    lastContactedAt: "2026-06-03",
  },
  {
    id: "lead-006",
    name: "Kavitha Rajan",
    email: "kavitha@email.com",
    phone: "+91 98765 66666",
    city: "Bengaluru",
    plotSize: "2,000 sq.ft",
    builtUpArea: "1,500 sq.ft",
    budgetRange: "₹40 – 60 Lakhs",
    homeType: "independent_house",
    servicesNeeded: ["Construction Planning", "Progress Tracking"],
    timeline: "Within 1 month",
    preferredContact: "whatsapp",
    notes: "Referred by Vikram Patel. Has approved house plan.",
    status: "new",
    createdAt: "2026-06-14",
  },
];

// ============================================
// Mock Notifications
// ============================================

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-001",
    title: "New Progress Update",
    message: "Arjun uploaded new progress for Patel Residence — Wall work",
    type: "info",
    read: false,
    createdAt: "2026-06-14T17:30:00",
    link: "/progress",
  },
  {
    id: "notif-002",
    title: "Payment Due Soon",
    message: "Column & Wall Stage payment of ₹7,56,000 is due on Jan 15",
    type: "warning",
    read: false,
    createdAt: "2026-06-14T10:00:00",
    link: "/payments",
  },
  {
    id: "notif-003",
    title: "Document Uploaded",
    message: "Material Quality Certificate has been uploaded to your project",
    type: "success",
    read: true,
    createdAt: "2026-06-13T14:00:00",
    link: "/documents",
  },
];

// ============================================
// Mock Admin Stats
// ============================================

export const MOCK_ADMIN_STATS: AdminStats = {
  totalCustomers: 156,
  activeProjects: 43,
  newEnquiries: 12,
  pendingPayments: 18,
  overdueTasks: 3,
  todayUpdates: 28,
  totalRevenue: 28500000,
  monthlyEnquiries: [
    { month: "Jan", count: 18 },
    { month: "Feb", count: 22 },
    { month: "Mar", count: 28 },
    { month: "Apr", count: 24 },
    { month: "May", count: 32 },
    { month: "Jun", count: 38 },
  ],
  projectStatusBreakdown: [
    { status: "Active", count: 43 },
    { status: "Completed", count: 98 },
    { status: "On Hold", count: 8 },
    { status: "Planning", count: 7 },
  ],
  revenueByMonth: [
    { month: "Jan", amount: 4200000 },
    { month: "Feb", amount: 3800000 },
    { month: "Mar", amount: 5100000 },
    { month: "Apr", amount: 4600000 },
    { month: "May", amount: 5200000 },
    { month: "Jun", amount: 5600000 },
  ],
};

// ============================================
// Mock All Projects (for admin)
// ============================================

export const MOCK_ALL_PROJECTS: Project[] = [
  MOCK_PROJECT,
  {
    id: "proj-002",
    name: "Sharma Villa",
    customerId: "cust-002",
    customerName: "Priya Sharma",
    siteAddress: "Plot 78, Green Valley, Jubilee Hills",
    city: "Hyderabad",
    plotSize: "3,000 sq.ft",
    builtUpArea: "2,400 sq.ft",
    startDate: "2025-08-15",
    expectedCompletion: "2026-08-30",
    currentStage: "foundation",
    status: "in_progress",
    completionPercentage: 18,
    assignedEngineer: "Ravi Kumar",
    totalValue: 5040000,
    amountPaid: 1008000,
    milestones: [],
  },
  {
    id: "proj-003",
    name: "Irfan Residence",
    customerId: "cust-003",
    customerName: "Mohammed Irfan",
    siteAddress: "Plot 15, Lake View, Anna Nagar",
    city: "Chennai",
    plotSize: "1,800 sq.ft",
    builtUpArea: "1,400 sq.ft",
    startDate: "2025-04-01",
    expectedCompletion: "2026-02-28",
    currentStage: "electrical",
    status: "in_progress",
    completionPercentage: 78,
    assignedEngineer: "Arjun Nair",
    totalValue: 2940000,
    amountPaid: 2352000,
    milestones: [],
  },
  {
    id: "proj-004",
    name: "Begum Palace",
    customerId: "cust-004",
    customerName: "Fatima Begum",
    siteAddress: "Plot 5, Palm Grove, Koramangala",
    city: "Bengaluru",
    plotSize: "4,000 sq.ft",
    builtUpArea: "3,200 sq.ft",
    startDate: "2026-07-01",
    expectedCompletion: "2027-10-31",
    currentStage: "planning",
    status: "not_started",
    completionPercentage: 0,
    assignedEngineer: "Unassigned",
    totalValue: 8960000,
    amountPaid: 896000,
    milestones: [],
  },
];
